// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommonLayout: typeof import('./components/Layout/CommonLayout.vue')['default']
    DefaultLoading: typeof import('./components/Loading/DefaultLoading.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    EmptyLayout: typeof import('./components/Layout/EmptyLayout.vue')['default']
    FlexBar: typeof import('./components/FlexBar.vue')['default']
    HeaderLayout: typeof import('./components/Layout/HeaderLayout.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IEpArrowDown: typeof import('~icons/ep/arrow-down')['default']
    IEpMoon: typeof import('~icons/ep/moon')['default']
    IEpSunny: typeof import('~icons/ep/sunny')['default']
    LocaleSwitch: typeof import('./components/LocaleSwitch.vue')['default']
    Login: typeof import('./components/Form/Login/index.vue')['default']
    MarqueeText: typeof import('./components/MarqueeText/index.vue')['default']
    NumberInput: typeof import('./components/Widgets/NumberInput.vue')['default']
    PaginationTable: typeof import('./components/Table/PaginationTable.vue')['default']
    PasswordForm: typeof import('./components/Form/PasswordForm.vue')['default']
    RouteItem: typeof import('./components/Menu/RouteItem.vue')['default']
    RouteMenu: typeof import('./components/Menu/RouteMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheMarquee: typeof import('./components/TheMarquee/index.vue')['default']
    ThemeChange: typeof import('./components/ThemeChange/index.vue')['default']
    ThemeSwitch: typeof import('./components/ThemeSwitch.vue')['default']
    ToggleDark: typeof import('./components/ToggleDark.vue')['default']
    UserForm: typeof import('./components/Form/UserForm.vue')['default']
  }
}

export {}
